osx_image: xcode7.3
language: objective-c

cache:
- bundler
- cocoapods

install:
- bundle install
- bundle exec pod repo update --silent
- bundle exec pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/Trustbadge.xcworkspace -scheme Trustbadge_Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
- pod lib lint --quick

after_success: slather coverage -c -s -t
