osx_image: xcode7.3
language: objective-c

cache:
- bundler
- cocoapods

install:
- bundle install
- bundle exec pod repo update --silent
- bundle exec pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/Trustbadge.xcworkspace -scheme Trustbadge_Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s' -derivedDataPath ${TRAVIS_BUILD_DIR}/myDerivedData ONLY_ACTIVE_ARCH=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
- pod lib lint --quick

after_success: slather coverage -c -s -t --ignore '../*' -b ${TRAVIS_BUILD_DIR}/myDerivedData --verbose
